runtime: python27
api_version: 1
threadsafe: true
service: backend

builtins:
- remote_api: on

handlers:
- url: /.*
  script: main.app

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'orderly-life'

libraries:
- name: ssl
  version: latest
